# Generated by Django 2.1.7 on 2019-03-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('Patient', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='prescription/pdfs/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='prescription/covers/')),
            ],
        ),
    ]
