# Generated by Django 2.1.7 on 2019-03-31 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='Patient',
            new_name='patient',
        ),
    ]
